version: "2"

volumes:
  gems:
    driver: local

services:
  belugas_ruby:
    image: gueils/belugas-ruby:development
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
    stdin_open: true
    tty: true
